---
- name: Install docker
  when: ansible_local["bin"]["docker"] == ""
  block:
    - name: Install dependencies
      become: yes
      become_user: root
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
        state: present

    - name: Ensure APT keyrings directory exists
      become: yes
      become_user: root
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker GPG key
      become: yes
      become_user: root
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker repository
      become: yes
      become_user: root
      apt_repository:
        repo: deb [arch={{ ansible_local["arch"]["package"] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable
        state: present
        filename: docker

    - name: Install Docker
      become: yes
      become_user: root
      package:
        name:
          - docker-ce
        state: present
        update_cache: true

- name: Enable the docker service
  when: ansible_local["docker"]["service_enabled"] == false
  become: yes
  become_user: root
  service:
    name: docker
    state: started
    enabled: true

- name: Add user to the docker group
  when: ansible_local["docker"]["group_set"] == false
  block:
    - name: Ensure ansible user is added to the docker group
      become: yes
      become_user: root
      user:
        name: "{{ ansible_user }}"
        groups: ["docker"]
        append: true

    - name: Reboot the machine to guarantee that groups have been applied
      become: yes
      become_user: root
      reboot:
        reboot_timeout: 900