all:
  children:
    k3d:
      children:
        single_nodes:
          hosts:
            k3d0:
        servers:
        agents:
      vars:
        ansible_user: user
        ansible_python_interpreter: /usr/bin/python3
        k3d_version: 5.6.3
        kubectl_version: 1.28.15
        suc_version: 0.19.0
