all:
  children:
    k3d:
      children:
        single_nodes:
          hosts:
            k3d0.iot:
        servers:
        agents:
      vars:
        ansible_user: user
        ansible_python_interpreter: /usr/bin/python3
        k3d_version: 5.9.0
        kubectl_version: 1.35.0
        suc_version: 0.20.1
